// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProPlanterAPI.Models;

namespace ProPlanterAPI.Migrations
{
    [DbContext(typeof(MyPlantContext))]
    [Migration("20200809232501_AddedMyPlantRemovedAge")]
    partial class AddedMyPlantRemovedAge
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProPlanterAPI.Models.MyPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatePlanted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FertilizeFrequency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastFertilizedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastWateredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WaterFrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MyPlantItems");
                });
#pragma warning restore 612, 618
        }
    }
}
